In [2]:
import pandas as pd

# Create two sample DataFrames
data1 = {
    'EmployeeID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'Finance', 'IT']
}

data2 = {
    'EmployeeID': [2, 4, 3, 5],
    'Salary': [70000, 80000, 60000, 90000]
}

# Convert dictionaries to DataFrames
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Display the original DataFrames
print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)

# Merge the DataFrames on 'EmployeeID' using an inner join
merged_df = pd.merge(df1, df2, on='EmployeeID', how='inner')

DataFrame 1:
   EmployeeID     Name Department
0           1    Alice         HR
1           2      Bob         IT
2           3  Charlie    Finance
3           4    David         IT

DataFrame 2:
   EmployeeID  Salary
0           2   70000
1           4   80000
2           3   60000
3           5   90000

In [3]:
merged_df1 = pd.merge(df1, df2, on='EmployeeID', how='left')
merged_df1

   EmployeeID     Name Department   Salary
0           1    Alice         HR      NaN
1           2      Bob         IT  70000.0
2           3  Charlie    Finance  60000.0
3           4    David         IT  80000.0

In [4]:
merged_df2 = pd.merge(df1, df2, on='EmployeeID', how='right')
merged_df2

   EmployeeID     Name Department  Salary
0           2      Bob         IT   70000
1           4    David         IT   80000
2           3  Charlie    Finance   60000
3           5      NaN        NaN   90000

In [5]:
merged_df3 = pd.merge(df1, df2, on='EmployeeID', how='outer')
merged_df3

   EmployeeID     Name Department   Salary
0           1    Alice         HR      NaN
1           2      Bob         IT  70000.0
2           3  Charlie    Finance  60000.0
3           4    David         IT  80000.0
4           5      NaN        NaN  90000.0

In [6]:
merged_df3 = pd.merge(df1, df2, how='cross')
merged_df3

    EmployeeID_x     Name Department  EmployeeID_y  Salary
0              1    Alice         HR             2   70000
1              1    Alice         HR             4   80000
2              1    Alice         HR             3   60000
3              1    Alice         HR             5   90000
4              2      Bob         IT             2   70000
5              2      Bob         IT             4   80000
6              2      Bob         IT             3   60000
7              2      Bob         IT             5   90000
8              3  Charlie    Finance             2   70000
9              3  Charlie    Finance             4   80000
10             3  Charlie    Finance             3   60000
11             3  Charlie    Finance             5   90000
12             4    David         IT             2   70000
13             4    David         IT             4   80000
14             4    David         IT             3   60000
15             4    David         IT             5   90000

In [10]:
df1

               Name Department
EmployeeID
1             Alice         HR
2               Bob         IT
3           Charlie    Finance
4             David         IT

In [12]:

joined_df_inner=df1.join(df2,how='inner')

In [13]:
joined_df_inner

               Name Department  Salary
EmployeeID
2               Bob         IT   70000
3           Charlie    Finance   60000
4             David         IT   80000