In [1]:
import pandas as pd
import numpy as np

# Creating a more complex dataframe with multi-index
index = pd.MultiIndex.from_tuples([('New York', 'Q1', 'one'), ('New York', 'Q1', 'two'),
                                   ('Los Angeles', 'Q1', 'one'), ('Los Angeles', 'Q1', 'two'),
                                   ('Chicago', 'Q2', 'one'), ('Chicago', 'Q2', 'two'),
                                   ('New York', 'Q2', 'one'), ('New York', 'Q2', 'two')],
                                  names=['City', 'Quarter', 'ID'])

# Creating random data for Sales, Profit, and Quantity
sales = np.round(np.random.uniform(100, 500, 8), 2)  # Sales between 100 and 500
profit = np.round(np.random.uniform(0, 0.35, 8), 2)     # Profit between 0 and 0.35
quantity = np.random.randint(1, 20, 8)               # Quantity as integers

# Creating the dataframe
df_multi = pd.DataFrame({'Sales': sales, 'Profit(%)': profit, 'Quantity': quantity}, index=index)

print(df_multi)

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  164.94       0.21        15
                    two  322.82       0.26        14
Los Angeles Q1      one  195.99       0.11         9
                    two  224.61       0.31         8
Chicago     Q2      one  341.04       0.24         7
                    two  400.65       0.05         6
New York    Q2      one  458.88       0.10        18
                    two  394.30       0.32        16

In [11]:
print(df_multi.loc['Chicago', 'Sales'])

Quarter  ID
Q2       one    341.04
         two    400.65
Name: Sales, dtype: float64

C:\Users\DELL\AppData\Local\Temp\ipykernel_9448\3604561633.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  print(df_multi.loc['Chicago', 'Sales'])

In [15]:
print(df_multi.loc[('New York', 'Q2'),'Profit(%)'])

ID
one    0.10
two    0.32
Name: Profit(%), dtype: float64

C:\Users\DELL\AppData\Local\Temp\ipykernel_9448\2219958533.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  print(df_multi.loc[('New York', 'Q2'),'Profit(%)'])

In [16]:
print(df_multi.loc[(['New York', 'Chicago'], 'Q2'), 'Profit(%)'])

City      Quarter  ID
New York  Q2       one    0.10
                   two    0.32
Chicago   Q2       one    0.24
                   two    0.05
Name: Profit(%), dtype: float64

In [17]:
print(df_multi.loc[(['New York', 'Chicago'], 'Q2'), ['Profit(%)','Quantity']])

                      Profit(%)  Quantity
City     Quarter ID
New York Q2      one       0.10        18
                 two       0.32        16
Chicago  Q2      one       0.24         7
                 two       0.05         6

In [20]:
print(df_multi.loc[('Chicago', 'Q2'),'Sales'])

ID
one    341.04
two    400.65
Name: Sales, dtype: float64

C:\Users\DELL\AppData\Local\Temp\ipykernel_9448\2276367391.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  print(df_multi.loc[('Chicago', 'Q2'),'Sales']).reset_index()

AttributeError: 'NoneType' object has no attribute 'reset_index'

In [30]:
print(df_multi.loc[(slice(None),slice(None),"one"),:])

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  164.94       0.21        15
Los Angeles Q1      one  195.99       0.11         9
Chicago     Q2      one  341.04       0.24         7
New York    Q2      one  458.88       0.10        18

In [31]:
print(df_multi.loc[(slice(None),"Q1",slice(None)),:])

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  164.94       0.21        15
                    two  322.82       0.26        14
Los Angeles Q1      one  195.99       0.11         9
                    two  224.61       0.31         8

In [37]:
print(df_multi[df_multi['Sales'] > 200])

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      two  322.82       0.26        14
Los Angeles Q1      two  224.61       0.31         8
Chicago     Q2      one  341.04       0.24         7
                    two  400.65       0.05         6
New York    Q2      one  458.88       0.10        18
                    two  394.30       0.32        16

In [42]:
print(df_multi[df_multi['Quantity'] > 10]['Quantity'])

City      Quarter  ID
New York  Q1       one    15
                   two    14
          Q2       one    18
                   two    16
Name: Quantity, dtype: int32

In [43]:
print(df_multi[df_multi['Quantity'] > 10][['Quantity','Profit(%)']])

                      Quantity  Profit(%)
City     Quarter ID
New York Q1      one        15       0.21
                 two        14       0.26
         Q2      one        18       0.10
                 two        16       0.32

In [44]:
df_multi["Sales"].idxmax()

('New York', 'Q2', 'one')

In [45]:
df_multi[df_multi["Profit(%)"]>0.2]

                          Sales  Profit(%)  Quantity
City        Quarter ID
New York    Q1      one  164.94       0.21        15
                    two  322.82       0.26        14
Los Angeles Q1      two  224.61       0.31         8
Chicago     Q2      one  341.04       0.24         7
New York    Q2      two  394.30       0.32        16

In [46]:
df_multi.groupby("City")['Sales'].mean()

City
Chicago        370.845
Los Angeles    210.300
New York       335.235
Name: Sales, dtype: float64

In [47]:
df_multi.groupby("Quarter").size()

Quarter
Q1    4
Q2    4
dtype: int64

In [48]:
df_multi.loc[(slice(None),slice(None))].shape

(8, 3)

In [49]:
df_multi.groupby("Quarter").count()

         Sales  Profit(%)  Quantity
Quarter
Q1           4          4         4
Q2           4          4         4

In [54]:
df_multi.index.get_level_values("Quarter").value_counts()

Quarter
Q1    4
Q2    4
Name: count, dtype: int64