In [1]:
import pandas as pd

In [2]:
data = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [24, 27, 22],
'City': ['New York', 'Los Angeles', 'Chicago']
}
df=pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

In [3]:
df.head(2)# 5 rows from up

    Name  Age         City
0  Alice   24     New York
1    Bob   27  Los Angeles

In [4]:
df.tail(1)# 5rows from last

      Name  Age     City
2  Charlie   22  Chicago

In [5]:
print(df.info())
print(df.describe())

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   City    3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes
None
             Age
count   3.000000
mean   24.333333
std     2.516611
min    22.000000
25%    23.000000
50%    24.000000
75%    25.500000
max    27.000000

In [6]:
print(df["Name"])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [7]:
print(df["Age"].mean())

24.333333333333332

In [8]:
print(df[["Age","Name"]])

   Age     Name
0   24    Alice
1   27      Bob
2   22  Charlie

In [9]:
print(df.iloc[0])# first row
print(df.loc[1])#row with index

Name       Alice
Age           24
City    New York
Name: 0, dtype: object
Name            Bob
Age              27
City    Los Angeles
Name: 1, dtype: object

In [10]:
pip install kagglehub

Requirement already satisfied: kagglehub in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (0.1.19)
Requirement already satisfied: packaging in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (26.1)
Requirement already satisfied: pyyaml in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (2.33.1)
Requirement already satisfied: tqdm in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.1)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (2026.2.25)
Requirement already satisfied: colorama in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [11]:
pip install kagglehub

Requirement already satisfied: kagglehub in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (0.1.19)
Requirement already satisfied: packaging in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (26.1)
Requirement already satisfied: pyyaml in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (2.33.1)
Requirement already satisfied: tqdm in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.1)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->kagglehub) (2026.2.25)
Requirement already satisfied: colorama in C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [12]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "data_science_student_marks.csv"


# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "sudhirsingh108/data-science-students",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

C:\Users\DELL\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\DELL\AppData\Local\Temp\ipykernel_2008\1977989171.py:9: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

First 5 records:    student_id location  age  sql_marks  excel_marks  python_marks  \
0           4   Sydney   24         95           99            87
1           5    Tokyo   24         99           95            89
2           6   Berlin   22         72           70            99
3           7   London   23         97           90            74
4           8    Tokyo   22         91           71            79

   power_bi_marks  english_marks
0              82             75
1              86             82
2              79             77
3              72             85
4              80             75

In [13]:
df=pd.read_csv("C:\\Users\\DELL\\Desktop\\data_science_student_marks.csv")

In [14]:
df.head()

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   student_id      497 non-null    int64
 1   location        497 non-null    str
 2   age             497 non-null    int64
 3   sql_marks       497 non-null    int64
 4   excel_marks     497 non-null    int64
 5   python_marks    497 non-null    int64
 6   power_bi_marks  497 non-null    int64
 7   english_marks   497 non-null    int64
dtypes: int64(7), str(1)
memory usage: 31.2 KB

In [16]:
print(df.loc[1])

student_id            5
location          Tokyo
age                  24
sql_marks            99
excel_marks          95
python_marks         89
power_bi_marks       86
english_marks        82
Name: 1, dtype: object

In [17]:
df["location"].unique()

<StringArray>
[     'Sydney',       'Tokyo',      'Berlin',      'London',     'Toronto',
   'Melbourne',       'Paris', 'Los Angeles',    'New York']
Length: 9, dtype: str

In [18]:
df["location"].value_counts()

location
Tokyo          60
Los Angeles    60
Melbourne      58
New York       57
Toronto        56
Paris          55
Sydney         53
Berlin         52
London         46
Name: count, dtype: int64

In [19]:
df["sql_marks"].mean()

np.float64(84.66197183098592)

In [36]:
df.iloc[1:6]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
5,9,Toronto,20,93,88,75,93,72

In [20]:
df.iloc[[1,6]]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
1,5,Tokyo,24,99,95,89,86,82
6,10,Tokyo,18,77,87,100,98,93

In [21]:
df.iloc[1:6,0:2]

   student_id location
1           5    Tokyo
2           6   Berlin
3           7   London
4           8    Tokyo
5           9  Toronto

In [22]:
df.iloc[[1,21]]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
1,5,Tokyo,24,99,95,89,86,82
21,25,Paris,20,92,98,94,74,77

In [26]:
first20 = df.iloc[:20, 7]

In [27]:
first20

0      75
1      82
2      77
3      85
4      75
5      72
6      93
7      72
8      94
9      86
10     96
11     71
12     84
13     85
14     71
15     83
16     98
17     96
18     85
19    100
Name: english_marks, dtype: int64

In [28]:
first20.mean()

np.float64(84.0)

In [29]:
first20.max()

np.int64(100)

In [31]:
first20.idxmax()

19

In [32]:
first20.min()

np.int64(71)

In [33]:
print(df.iloc[1:4,[0,2]])

   student_id  age
1           5   24
2           6   22
3           7   23

In [34]:
df.iloc[:,2].mean()

np.float64(21.380281690140844)

In [35]:
print("the averag student age is : ",df["age"].mean())

the averag student age is :  21.380281690140844

In [37]:
df["age"].value_counts()

age
21    76
19    72
20    68
22    65
23    60
25    60
18    52
24    44
Name: count, dtype: int64

In [38]:
df["location"].value_counts()

location
Tokyo          60
Los Angeles    60
Melbourne      58
New York       57
Toronto        56
Paris          55
Sydney         53
Berlin         52
London         46
Name: count, dtype: int64

In [39]:
df.loc[0]

student_id             4
location          Sydney
age                   24
sql_marks             95
excel_marks           99
python_marks          87
power_bi_marks        82
english_marks         75
Name: 0, dtype: object

In [40]:
df.loc[0,"student_id"]

np.int64(4)

In [42]:
df.loc[0, ["student_id", "age"]]

student_id     4
age           24
Name: 0, dtype: int64

In [43]:
df.loc[0:3, ["student_id", "age"]]

   student_id  age
0           4   24
1           5   24
2           6   22
3           7   23

In [45]:
df.loc[[10,20], ["student_id", "age"]]

    student_id  age
10          14   20
20          24   20

In [50]:
print(df.loc[df["age"] > 23].shape)

(104, 8)

In [51]:
df[df["age"]>=23]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
3,7,London,23,97,90,74,72,85
8,12,Melbourne,24,80,95,87,90,94
11,15,Paris,24,94,93,87,80,71
...,...,...,...,...,...,...,...,...
488,492,London,23,85,73,78,81,96
489,493,Los Angeles,24,94,74,80,92,95
490,494,Melbourne,25,84,96,72,93,86
491,495,New York,24,83,78,82,84,84
492,496,New York,23,71,92,98,78,88

In [56]:
df[df["python_marks"]>95]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
2,6,Berlin,22,72,70,99,79,77
6,10,Tokyo,18,77,87,100,98,93
9,13,London,19,97,80,96,97,86
14,18,Melbourne,19,89,76,96,93,71
18,22,Los Angeles,22,83,73,100,75,85
...,...,...,...,...,...,...,...,...
460,464,New York,25,96,76,97,75,84
469,473,Los Angeles,23,76,89,98,80,94
472,476,Melbourne,20,95,82,96,93,70
481,485,Paris,21,89,98,96,83,79
492,496,New York,23,71,92,98,78,88

In [57]:
df[df["python_marks"]>95].shape[0]/df.shape[0]*100# نجيب عددهم ونقسم على العدد الكلي ونضرب في 100

16.901408450704224

In [58]:
no_ofStudent=df[df["python_marks"]>95].shape[0]
allstd=df.shape[0]
persentage=(no_ofStudent/allstd)*100
persentage

16.901408450704224

In [60]:
df_sorted=df.sort_values(by="age")
df_sorted

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
19,23,New York,18,80,73,94,89,100
22,26,Sydney,18,90,91,89,94,93
486,490,Tokyo,18,87,100,95,89,85
52,56,Tokyo,18,87,99,79,92,70
325,329,Sydney,18,98,95,82,77,76
...,...,...,...,...,...,...,...,...
71,75,Los Angeles,25,99,79,92,92,84
466,470,Toronto,25,82,70,83,72,97
53,57,Sydney,25,87,89,70,83,71
24,28,Los Angeles,25,84,85,82,96,75
16,20,Berlin,25,92,87,81,79,98

In [61]:
df.columns

Index(['student_id', 'location', 'age', 'sql_marks', 'excel_marks',
       'python_marks', 'power_bi_marks', 'english_marks'],
      dtype='str')

In [66]:
df[(df["age"] >= 22) & (df["age"] <= 24)]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
489,493,Los Angeles,24,94,74,80,92,95
491,495,New York,24,83,78,82,84,84
492,496,New York,23,71,92,98,78,88
494,498,Paris,22,78,80,78,71,70
496,500,London,22,85,87,93,70,86

In [65]:
conditon1=df["age"] >= 22
conditon2= df["age"] <= 24  
df[conditon1 & conditon2]

,student_id,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,London,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
489,493,Los Angeles,24,94,74,80,92,95
491,495,New York,24,83,78,82,84,84
492,496,New York,23,71,92,98,78,88
494,498,Paris,22,78,80,78,71,70
496,500,London,22,85,87,93,70,86

In [72]:
condition1 = df["sql_marks"] > 90
condition2 = df["excel_marks"] > 90
retrieve = df[condition1 & condition2]
retrieve[["student_id","age"]]

     student_id  age
0             4   24
1             5   24
11           15   24
21           25   20
33           37   23
34           38   21
47           51   23
55           59   21
56           60   19
77           81   22
87           91   21
88           92   18
103         107   24
116         120   20
118         122   24
134         138   18
153         157   23
157         161   25
170         174   25
185         189   19
197         201   25
208         212   23
274         278   22
302         306   22
305         309   19
320         324   19
325         329   18
349         353   24
362         366   19
364         368   18
367         371   23
372         376   23
382         386   19
383         387   19
406         410   25
412         416   22
428         432   18
435         439   21
453         457   22
461         465   22
495         499   21

In [77]:
df["location"].replace("London","LON")

0           Sydney
1            Tokyo
2           Berlin
3              LON
4            Tokyo
          ...
492       New York
493    Los Angeles
494          Paris
495    Los Angeles
496            LON
Name: location, Length: 497, dtype: str

In [79]:
df.set_index("student_id")

,location,age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
student_id,,,,,,,
4,Sydney,24,95,99,87,82,75
5,Tokyo,24,99,95,89,86,82
6,Berlin,22,72,70,99,79,77
7,LON,23,97,90,74,72,85
8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...
496,New York,23,71,92,98,78,88
497,Los Angeles,20,90,100,90,78,73
498,Paris,22,78,80,78,71,70
499,Los Angeles,21,96,93,78,78,82
500,LON,22,85,87,93,70,86

In [82]:
df.rename(columns={"location":"Country","age":"Age"},inplace=True)
df

,student_id,country,Age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,LON,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82
496,500,LON,22,85,87,93,70,86

In [83]:
df[df["country"].isin(["Sydney","Tokyo"])]

,student_id,country,Age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Sydney,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
4,8,Tokyo,22,91,71,79,80,75
6,10,Tokyo,18,77,87,100,98,93
12,16,Tokyo,19,73,82,78,70,84
...,...,...,...,...,...,...,...,...
465,469,Sydney,20,86,99,82,92,88
467,471,Tokyo,22,94,71,84,87,70
474,478,Tokyo,21,98,89,94,75,97
477,481,Sydney,24,70,79,80,83,78
486,490,Tokyo,18,87,100,95,89,85

In [85]:
df[df["Age"].between(20,23)]

,student_id,country,Age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
2,6,Berlin,22,72,70,99,79,77
3,7,LON,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
5,9,Toronto,20,93,88,75,93,72
7,11,Toronto,21,78,90,88,79,72
...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82
496,500,LON,22,85,87,93,70,86

In [86]:
df.isnull().sum()

student_id        0
country           0
Age               0
sql_marks         0
excel_marks       0
python_marks      0
power_bi_marks    0
english_marks     0
dtype: int64

In [90]:
import numpy as np
df.loc[0, "country"] = np.nan
df

,student_id,country,Age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,NaN,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,LON,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82
496,500,LON,22,85,87,93,70,86

In [91]:
df.isnull().sum()

student_id        0
country           1
Age               0
sql_marks         0
excel_marks       0
python_marks      0
power_bi_marks    0
english_marks     0
dtype: int64

In [94]:
df.fillna({"country": df["country"].mode()}, inplace=True)# replace tha nan

,student_id,country,Age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Los Angeles,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,LON,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82
496,500,LON,22,85,87,93,70,86

In [95]:
df.duplicated().sum()

np.int64(0)

In [100]:
df = df.drop_duplicates()
df

,student_id,country,Age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks
0,4,Los Angeles,24,95,99,87,82,75
1,5,Tokyo,24,99,95,89,86,82
2,6,Berlin,22,72,70,99,79,77
3,7,LON,23,97,90,74,72,85
4,8,Tokyo,22,91,71,79,80,75
...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88
493,497,Los Angeles,20,90,100,90,78,73
494,498,Paris,22,78,80,78,71,70
495,499,Los Angeles,21,96,93,78,78,82
496,500,LON,22,85,87,93,70,86

In [102]:
df["python_status"] = df["python_marks"].map(lambda x: "pass" if x >= 60 else "fail")
df

,student_id,country,Age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks,python_status
0,4,Los Angeles,24,95,99,87,82,75,pass
1,5,Tokyo,24,99,95,89,86,82,pass
2,6,Berlin,22,72,70,99,79,77,pass
3,7,LON,23,97,90,74,72,85,pass
4,8,Tokyo,22,91,71,79,80,75,pass
...,...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88,pass
493,497,Los Angeles,20,90,100,90,78,73,pass
494,498,Paris,22,78,80,78,71,70,pass
495,499,Los Angeles,21,96,93,78,78,82,pass
496,500,LON,22,85,87,93,70,86,pass

In [104]:
import numpy as np
df["python_status"] = np.where(df["python_marks"] >= 60, "pass", "fail")
df

,student_id,country,Age,sql_marks,excel_marks,python_marks,power_bi_marks,english_marks,python_status
0,4,Los Angeles,24,95,99,87,82,75,pass
1,5,Tokyo,24,99,95,89,86,82,pass
2,6,Berlin,22,72,70,99,79,77,pass
3,7,LON,23,97,90,74,72,85,pass
4,8,Tokyo,22,91,71,79,80,75,pass
...,...,...,...,...,...,...,...,...,...
492,496,New York,23,71,92,98,78,88,pass
493,497,Los Angeles,20,90,100,90,78,73,pass
494,498,Paris,22,78,80,78,71,70,pass
495,499,Los Angeles,21,96,93,78,78,82,pass
496,500,LON,22,85,87,93,70,86,pass

In [106]:
locationGrube=df.groupby("country")
locationGrube

In [110]:
g=df.groupby("country")
g["python_marks"].mean()

country
Berlin         85.653846
LON            85.521739
Los Angeles    85.557377
Melbourne      83.637931
New York       86.771930
Paris          85.381818
Sydney         84.230769
Tokyo          86.033333
Toronto        85.642857
Name: python_marks, dtype: float64

In [114]:
g = df.groupby("country")
g["python_marks"].max()["Paris"]
g["python_marks"].idxmax()["Paris"]

np.int64(264)